%Base de datos español-ingles.
%Simbologia.
%fe: femenino, ma: masculino, def: definido, ind:indefinido
%plu: plural, sin: singular, neu: neutro
%ad: antes de, dd: despues de, pri: primera persona
%seg: segunda persona, ter: tercera persona
%pre: presente, pas: pasado.

%Articles
%Spa
artEs(fe,sin,def,la).
artEs(ma,sin,def,el).
artEs(fe,plu,def,las).
artEs(ma,plu,def,los).
artEs(fe,sin,ind,una).
artEs(ma,sin,ind,un).
artEs(fe,plu,ind,unas).
artEs(ma,plu,ind,unos).
artEs(_,sin,neu,lo).
%Eng
artEn(_,def,the).
%artEn(sin,ind,(vow,an)).
%artEn(sin,ind,(con,a)).
artEn(sin,ind,a).
artEn(plu,ind,some).

%Pronouns(pronombres)
%Spa
pronEs(_,sin,pri,yo).
pronEs(ma,plu,pri,nosotros).
pronEs(fe,plu,pri,nosotras).
pronEs(_,sin,seg,usted).
pronEs(_,plu,seg,ustedes).
pronEs(ma,sin,ter,el).
pronEs(fe,sin,ter,ella).
pronEs(ma,plu,ter,ellos).
pronEs(fe,plu,tec,ellas).
%Eng
pronEn(_,sin,pri,i).
pronEn(_,plu,pri,we).
pronEn(_,_,seg,you).
pronEn(ma,sin,ter,he).
pronEn(fe,sin,ter,she).
pronEn(_,plu,ter,they).
pronEn(neu,sin,ter,it).

%Nouns(sustantivos)
sust(ma,sin,(hombre,man)).
sust(fe,sin,(mujer,woman)).
sust(ma,plu,(hombres,men)).
sust(fe,plu,(mujeres,women)).
sust(ma,sin,(gato,cat)).
sust(ma,plu,(gatos,cats)).
sust(ma,sin,(perro,dog)).
sust(ma,plu,(perros,dogs)).
sust(ma,sin,(libro,book)).
sust(ma,plu,(libros,books)).
sust(fe,sin,(casa,house)).
sust(fe,plu,(casas,houses)).
sust(ma,sin,(vaso,glass)).
sust(ma,plu,(vasos,glasses)).
sust(fe,sin,(taza,cup)).
sust(fe,plu,(tazas,cups)).
sust(fe,sin,(computadora,computer)).
sust(fe,plu,(computadoras,computers)).
sust(fe,sin,(ventana,window)).
sust(fe,plu,(ventanas,windows)).
sust(ma,sin,(sistema,system)).
sust(ma,plu,(sistemas,systems)).
sust(ma,sin,(cuenta,account)).
sust(ma,plu,(cuentas,accounts)).
sust(ma,sin,(teclado,keyboard)).
sust(ma,plu,(teclados,keyboards)).
sust(ma,sin,(piano,piano)).
sust(ma,plu,(pianos,pianos)).
sust(fe,sin,(mesa,table)).
sust(fe,plu,(mesas,tables)).
sust(fe,sin,(silla,chair)).
sust(fe,plu,(sillas,chairs)).
sust(fe,sin,(lugar,place)).
sust(fe,plu,(lugares,places)).
sust(ma,sin,(cuaderno,notebook)).
sust(ma,plu,(cuadernos,notebooks)).
sust(ma,sin,(lapiz,pencil)).
sust(ma,plu,(lapices,pencils)).
sust(ma,sin,(apunte,note)).
sust(ma,plu,(apuntes,notes)).
sust(ma,sin,(celular,smartphone)).
sust(ma,plu,(celulares,smartphones)).
sust(ma,sin,(lenguaje,language)).
sust(ma,plu,(lenguajes,languages)).
sust(ma,sin,(hola,hello)).
sust(ma,sin,(adios,goodbye)).
sust(ma,sin,(año,year)).
sust(ma,plu,(años,years)).
sust(ma,sin,(edad,age)).
sust(ma,plu,(edades,ages)).
sust(ma,sin,(primero,first)).
sust(ma,plu,(primeros,first)).
sust(fe,sin,(programacion,programming)).
sust(ma,sin,(dia,day)).
sust(ma,plu,(dias,days)).
sust(ma,sin,(linguistica,linguistics)).
sust(fe,sin,(inteligencia,intelligence)).
sust(ma,sin,(teorema,theorem)).
sust(ma,plu,(teoremas,theorems)).
sust(ma,sin,(patron,pattern)).
sust(ma,plu,(patrones,patterns)).
sust(ma,sin,(arbol,tree)).
sust(ma,plu,(arboles,trees)).
sust(ma,sin,(buscador,browser)).
sust(ma,sin,(motor,engine)).
sust(ma,plu,(motores,engines)).
sust(ma,sin,(carro,car)).
sust(ma,plu,(carros,cars)).
sust(fe,sin,(llave,key)).
sust(fe,plu,(llaves,keys)).
sust(ma,sin,(proyector,projector)).
sust(ma,plu,(proyectores,projectors)).
sust(fe,sin,(luz,light)).
sust(fe,plu,(luces,lights)).
sust(ma,sin,(estado,state)).
sust(ma,plu,(estados,states)).
sust(ma,sin,(juego,game)).
sust(ma,plu,(juegos,games)).
sust(fe,sin,(mochila,backpack)).
sust(fe,plu,(mochilas,backpacks)).
sust(fe,sin,(comida,food)).
sust(fe,plu,(comidas,foods)).
sust(ma,sin,(proyecto,project)).
sust(ma,plu,(proyectos,projects)).
sust(fe,sin,(cama,bed)).
sust(fe,plu,(camas,beds)).
sust(fe,sin,(foto,photo)).
sust(fe,plu,(fotos,photos)).
sust(ma,sin,(tiempo,time)).
sust(fe,plu,(veces,times)).
sust(ma,sin,(archivo,file)).
sust(ma,plu,(archivos,files)).
sust(ma,sin,(puntero,pointer)).
sust(ma,plu,(punteros,pointers)).
sust(fe,sin,(camisa,shirt)).
sust(fe,plu,(camisas,shirts)).
sust(ma,sin,(pantalon,trousers)).
sust(ma,plu,(pantalones,pants)).
sust(fe,sin,(pantaloneta,shorts)).
sust(fe,plu,(pantalonetas,shorts)).
sust(ma,sin,(zapato,shoe)).
sust(ma,plu,(zapatos,shoes)).
sust(ma,sin,(futbol,soccer)).
sust(fe,sin,(torre,tower)).
sust(fe,plu,(torres,towers)).
sust(ma,sin,(barco,ship)).
sust(ma,plu,(barcos,ships)).
sust(ma,sin,(muchacho,boy)).
sust(ma,plu,(muchachos,boys)).
sust(fe,sin,(muchacha,girl)).
sust(fe,plu,(muchachas,girls)).
sust(ma,sin,(dato,data)).
sust(ma,plu,(datos,data)).
sust(ma,sin,(codigo,code)).
sust(ma,plu,(codigos,codes)).
sust(fe,sin,(logica,logic)).
sust(ma,sin,(cinturon,belt)).
sust(ma,sin,(pan,bread)).
sust(fe,sin,(montaña,mountain)).
sust(fe,plu,(montañas,mountains)).
sust(ma,sin,(cafe,coffee)).
sust(ma,sin,(agua,water)).
sust(ma,sin,(analisis,parse)).
sust(ma,sin,(primero,first)).
sust(ma,plu,(primeros,first)).
sust(fe,sin,(primera,first)).
sust(fe,plu,(primeras,first)).
sust(ma,sin,(experto,expert)).
sust(ma,plu,(expertos,experts)).
sust(fe,sin,(comparacion,comparison)).
sust(fe,sin,(demostracion,demonstration)).
sust(ma,sin,(pareo,matching)).
sust(ma,sin,(prueba,proving)).
sust(ma,sin,(procesamiento,processing)).

%Adjectives
adj(fe,sin,_,(buena,good)).
adj(fe,plu,_,(buenas,good)).
adj(ma,sin,dd,(bueno,good)).
adj(ma,sin,ad,(buen,good)).
adj(ma,plu,_,(buenos,good)).
adj(ma,sin,dd,(caro,expensive)).
adj(ma,plu,dd,(caros,expensive)).
adj(fe,sin,dd,(cara,expensive)).
adj(fe,plu,dd,(caras,expensive)).
adj(_,sin,dd,(popular,popular)).
adj(_,plu,dd,(populares,popular)).
adj(_,sin,dd,(computacional,computational)).
adj(_,plu,dd,(computacionales,computational)).
adj(_,sin,dd,(artificial,artificial)).
adj(_,plu,dd,(artificiales,artificial)).
adj(ma,sin,dd,(experto,expert)).
adj(ma,plu,dd,(expertos,expert)).
adj(fe,sin,dd,(experta,expert)).
adj(fe,plu,dd,(expertas,expert)).
adj(_,sin,dd,(natural,natural)).
adj(_,plu,dd,(naturales,natural)).
adj(ma,sin,_,(bonito,pretty)).
adj(fe,sin,_,(bonita,pretty)).
adj(ma,sin,_,(viejo,old)).
adj(fe,sin,_,(vieja,old)).
adj(ma,sin,ad,(su,his)).
adj(ma,plu,ad,(sus,his)).
adj(fe,sin,ad,(su,hers)).
adj(fe,plu,ad,(sus,hers)).

%Adverbs
adv(hoy,today).
adv(ayer,yesterday).
adv(uno,one).
adv(comunmente,commonly).
adv(rapidamente,quickly).
adv(aqui,here).
adv(frecuentemente,frequently).
adv(raramente,rarely).
adv(aveces,sometimes).
adv(amenudo,often).
adv(muy,very).
adv(bastante,quite).
adv(internacionalmente,internationally).
adv(alla,there).

%Adposition
adp(ad,(a,to)).
adp(ad,(ante,before)).
adp(ad,(bajo,under)).
adp(ad,(con,with)).
adp(ad,(contra,against)).
adp(ad,(de,of)).
adp(ad,(desde,since)).
adp(ad,(en,in)).
adp(ad,(entre,between)).
adp(ad,(hacia,toward)).
adp(ad,(hasta,until)).
adp(ad,(para,for)).
adp(ad,(por,by)).
adp(ad,(segun,according)).
adp(ad,(sin,without)).
adp(ad,(sobre,on)).
adp(ad,(tras,after)).

%Conjunction
cjn(y,and).
cjn(o,or).
cjn(cuando,when).
cjn(como,as).
cjn(que,that).
cjn(porque,because).
cjn(aunque,although).
cjn(pero,but).

%Verbs
%Ser/To be
vrb(sin,pri,pre,(soy,am)).
vrb(plu,pri,pre,(somos,are)).
vrb(sin,seg,pre,(es,are)).
vrb(plu,seg,pre,(son,are)).
vrb(sin,ter,pre,(es,is)).
vrb(plu,ter,pre,(son,are)).
vrb(sin,pri,pas,(era,was)).
vrb(plu,pri,pas,(eramos,were)).
vrb(sin,seg,pas,(era,were)).
vrb(plu,seg,pas,(eran,were)).
vrb(sin,ter,pas,(era,was)).
vrb(plu,ter,pas,(eran,were)).
%Comer
vrb(sin,pri,pre,(como,eat)).
vrb(plu,pri,pre,(comemos,eat)).
vrb(sin,seg,pre,(come,eat)).
vrb(plu,seg,pre,(comen,eat)).
vrb(sin,ter,pre,(come,eats)).
vrb(plu,ter,pre,(comen,eat)).
vrb(sin,pri,pas,(comi,ate)).
vrb(plu,pri,pas,(comimos,ate)).
vrb(sin,seg,pas,(comio,ate)).
vrb(plu,seg,pas,(comieron,ate)).
vrb(sin,ter,pas,(comio,ate)).
vrb(plu,ter,pas,(comieron,ate)).
%Permanecer
vrb(sin,pri,pre,(permanezco,remain)).
vrb(plu,pri,pre,(permanecemos,remain)).
vrb(sin,seg,pre,(permanece,remain)).
vrb(plu,seg,pre,(permanecen,remain)).
vrb(sin,ter,pre,(permanece,remains)).
vrb(plu,ter,pre,(permanecen,remain)).
vrb(sin,pri,pas,(permanecia,remained)).
vrb(plu,pri,pas,(permaneciamos,remained)).
vrb(sin,seg,pas,(permanecia,remained)).
vrb(plu,seg,pas,(permanecian,remained)).
vrb(sin,ter,pas,(permanecia,remained)).
vrb(plu,ter,pas,(permanecian,remained)).
%Dormir
vrb(sin,pri,pre,(duermo,sleep)).
vrb(plu,pri,pre,(dormimos,sleep)).
vrb(sin,seg,pre,(duerme,sleep)).
vrb(plu,seg,pre,(duermen,sleep)).
vrb(sin,ter,pre,(duerme,sleeps)).
vrb(plu,ter,pre,(duermen,sleep)).
vrb(sin,pri,pas,(dormi,slept)).
vrb(plu,pri,pas,(dormimos,slept)).
vrb(sin,seg,pas,(dormio,slept)).
vrb(plu,seg,pas,(durmieron,slept)).
vrb(sin,ter,pas,(dormio,slept)).
vrb(plu,ter,pas,(durmieron,slept)).
%Jugar
vrb(sin,pri,pre,(juego,play)).
vrb(plu,pri,pre,(jugamos,play)).
vrb(sin,seg,pre,(juega,play)).
vrb(plu,seg,pre,(juegan,play)).
vrb(sin,ter,pre,(juega,plays)).
vrb(plu,ter,pre,(juegan,play)).
vrb(sin,pri,pas,(jugue,played)).
vrb(plu,pri,pas,(jugamos,played)).
vrb(sin,seg,pas,(jugo,played)).
vrb(plu,seg,pas,(jugaron,played)).
vrb(sin,ter,pas,(jugo,played)).
vrb(plu,ter,pas,(jugaron,played)).
%Trabajar
vrb(sin,pri,pre,(trabajo,work)).
vrb(plu,pri,pre,(trabajamos,work)).
vrb(sin,seg,pre,(trabaja,work)).
vrb(plu,seg,pre,(trabajan,work)).
vrb(sin,ter,pre,(trabaja,works)).
vrb(plu,ter,pre,(trabajan,work)).
vrb(sin,pri,pas,(trabaje,worked)).
vrb(plu,pri,pas,(trabajamos,worked)).
vrb(sin,seg,pas,(trabajo,worked)).
vrb(plu,seg,pas,(trabajaron,worked)).
vrb(sin,ter,pas,(trabajo,worked)).
vrb(plu,ter,pas,(trabajaron,worked)).
%Ir
vrb(sin,pri,pre,(voy,go)).
vrb(plu,pri,pre,(vamos,go)).
vrb(sin,seg,pre,(va,go)).
vrb(plu,seg,pre,(van,go)).
vrb(sin,ter,pre,(va,goes)).
vrb(plu,ter,pre,(van,go)).
vrb(sin,pri,pas,(fui,went)).
vrb(plu,pri,pas,(fuimos,went)).
vrb(sin,seg,pas,(fue,went)).
vrb(plu,seg,pas,(fueron,went)).
vrb(sin,ter,pas,(fue,went)).
vrb(plu,ter,pas,(fueron,went)).
%Comprar
vrb(sin,pri,pre,(compro,buy)).
vrb(plu,pri,pre,(compramos,buy)).
vrb(sin,seg,pre,(compra,buy)).
vrb(plu,seg,pre,(compran,buy)).
vrb(sin,ter,pre,(compra,buys)).
vrb(plu,ter,pre,(compran,buy)).
vrb(sin,pri,pas,(compre,bought)).
vrb(plu,pri,pas,(compramos,bought)).
vrb(sin,seg,pas,(compro,bought)).
vrb(plu,seg,pas,(compraron,bought)).
vrb(sin,ter,pas,(compro,bought)).
vrb(plu,ter,pas,(compraron,bought)).
%Entender
vrb(sin,pri,pre,(entiendo,understand)).
vrb(plu,pri,pre,(entendemos,understand)).
vrb(sin,seg,pre,(entiende,understand)).
vrb(plu,seg,pre,(entienden,understand)).
vrb(sin,ter,pre,(entiende,understands)).
vrb(plu,ter,pre,(entienden,understand)).
vrb(sin,pri,pas,(entendi,understood)).
vrb(plu,pri,pas,(entendimos,understood)).
vrb(sin,seg,pas,(entendio,understood)).
vrb(plu,seg,pas,(entendieron,understood)).
vrb(sin,ter,pas,(entendio,understood)).
vrb(plu,ter,pas,(entendieron,understood)).
%Usar
vrb(sin,pri,pre,(uso,use)).
vrb(plu,pri,pre,(usamos,use)).
vrb(sin,seg,pre,(usa,use)).
vrb(plu,seg,pre,(usan,use)).
vrb(sin,ter,pre,(usa,uses)).
vrb(plu,ter,pre,(usan,use)).
vrb(sin,pri,pas,(use,used)).
vrb(plu,pri,pas,(usamos,used)).
vrb(sin,seg,pas,(uso,used)).
vrb(plu,seg,pas,(usaron,used)).
vrb(sin,ter,pas,(uso,used)).
vrb(plu,ter,pas,(usaron,used)).
%Tener
vrb(sin,pri,pre,(tengo,have)).
vrb(plu,pri,pre,(tenemos,have)).
vrb(sin,seg,pre,(tiene,have)).
vrb(plu,seg,pre,(tienen,have)).
vrb(sin,ter,pre,(tiene,has)).
vrb(plu,ter,pre,(tienen,have)).
vrb(sin,pri,pas,(tuve,had)).
vrb(plu,pri,pas,(tuvimos,had)).
vrb(sin,seg,pas,(tuvo,had)).
vrb(plu,seg,pas,(tuvieron,had)).
vrb(sin,ter,pas,(tuvo,had)).
vrb(plu,ter,pas,(tuvieron,had)).
%Tomar
vrb(sin,pri,pre,(tomo,drink)).
vrb(plu,pri,pre,(tomamos,drink)).
vrb(sin,seg,pre,(toma,drink)).
vrb(plu,seg,pre,(toman,drink)).
vrb(sin,ter,pre,(toma,drinks)).
vrb(plu,ter,pre,(toman,drink)).
vrb(sin,pri,pas,(tome,drank)).
vrb(plu,pri,pas,(tomamos,drank)).
vrb(sin,seg,pas,(tomo,drank)).
vrb(plu,seg,pas,(tomaron,drank)).
vrb(sin,ter,pas,(tomo,drank)).
vrb(plu,ter,pas,(tomaron,drank)).
%Conducir
vrb(sin,pri,pre,(conduzo,drive)).
vrb(plu,pri,pre,(conducimos,drive)).
vrb(sin,seg,pre,(conduce,drive)).
vrb(plu,seg,pre,(conducen,drive)).
vrb(sin,ter,pre,(conduce,drives)).
vrb(plu,ter,pre,(conducen,drive)).
vrb(sin,pri,pas,(conduje,drove)).
vrb(plu,pri,pas,(condujiste,drove)).
vrb(sin,seg,pas,(condujo,drove)).
vrb(plu,seg,pas,(condujeron,drove)).
vrb(sin,ter,pas,(condujo,drove)).
vrb(plu,ter,pas,(condujeron,drove)).
%Escribir
vrb(sin,pri,pre,(escribo,write)).
vrb(plu,pri,pre,(escribimos,write)).
vrb(sin,seg,pre,(escribe,write)).
vrb(plu,seg,pre,(escriben,write)).
vrb(sin,ter,pre,(escribe,writes)).
vrb(plu,ter,pre,(escriben,write)).
vrb(sin,pri,pas,(escribi,wrote)).
vrb(plu,pri,pas,(escribimos,wrote)).
vrb(sin,seg,pas,(escribio,wrote)).
vrb(plu,seg,pas,(escribieron,wrote)).
vrb(sin,ter,pas,(escribio,wrote)).
vrb(plu,ter,pas,(escribieron,wrote)).
%Leer
vrb(sin,pri,pre,(leo,read)).
vrb(plu,pri,pre,(leemos,read)).
vrb(sin,seg,pre,(lee,read)).
vrb(plu,seg,pre,(leen,read)).
vrb(sin,ter,pre,(lee,reads)).
vrb(plu,ter,pre,(leen,read)).
vrb(sin,pri,pas,(lei,read)).
vrb(plu,pri,pas,(leimos,read)).
vrb(sin,seg,pas,(leyo,read)).
vrb(plu,seg,pas,(leyeron,read)).
vrb(sin,ter,pas,(leyo,read)).
vrb(plu,ter,pas,(leyeron,read)).
%Estudiar
vrb(sin,pri,pre,(estudio,study)).
vrb(plu,pri,pre,(estudiamos,study)).
vrb(sin,seg,pre,(estudia,study)).
vrb(plu,seg,pre,(estudian,study)).
vrb(sin,ter,pre,(estudia,studies)).
vrb(plu,ter,pre,(estudian,study)).
vrb(sin,pri,pas,(estudie,studied)).
vrb(plu,pri,pas,(estudiamos,studied)).
vrb(sin,seg,pas,(estudio,studied)).
vrb(plu,seg,pas,(estudiaron,studied)).
vrb(sin,ter,pas,(estudio,studied)).
vrb(plu,ter,pas,(estudiaron,studied)).
%Programar
vrb(sin,pri,pre,(programo,program)).
vrb(plu,pri,pre,(programamos,program)).
vrb(sin,seg,pre,(programa,program)).
vrb(plu,seg,pre,(programan,program)).
vrb(sin,ter,pre,(programa,programs)).
vrb(plu,ter,pre,(programan,program)).
vrb(sin,pri,pas,(programe,programmed)).
vrb(plu,pri,pas,(programamos,programmed)).
vrb(sin,seg,pas,(programo,programmed)).
vrb(plu,seg,pas,(programaron,programmed)).
vrb(sin,ter,pas,(programo,programmed)).
vrb(plu,ter,pas,(programaron,programmed)).
%Caminar
vrb(sin,pri,pre,(camino,walk)).
vrb(plu,pri,pre,(caminamos,walk)).
vrb(sin,seg,pre,(camina,walk)).
vrb(plu,seg,pre,(caminan,walk)).
vrb(sin,ter,pre,(camina,walks)).
vrb(plu,ter,pre,(caminan,walk)).
vrb(sin,pri,pas,(camine,walked)).
vrb(plu,pri,pas,(caminamos,walked)).
vrb(sin,seg,pas,(camino,walked)).
vrb(plu,seg,pas,(caminaron,walked)).
vrb(sin,ter,pas,(camino,walked)).
vrb(plu,ter,pas,(caminaron,walked)).
%Correr
vrb(sin,pri,pre,(corro,run)).
vrb(plu,pri,pre,(corremos,run)).
vrb(sin,seg,pre,(corre,run)).
vrb(plu,seg,pre,(corren,run)).
vrb(sin,ter,pre,(corre,runs)).
vrb(plu,ter,pre,(corren,run)).
vrb(sin,pri,pas,(corri,ran)).
vrb(plu,pri,pas,(corrimos,ran)).
vrb(sin,seg,pas,(corrio,ran)).
vrb(plu,seg,pas,(corrieron,ran)).
vrb(sin,ter,pas,(corrio,ran)).
vrb(plu,ter,pas,(corrieron,ran)).
%Nadar
vrb(sin,pri,pre,(nado,swim)).
vrb(plu,pri,pre,(nadamos,swim)).
vrb(sin,seg,pre,(nada,swim)).
vrb(plu,seg,pre,(nadan,swim)).
vrb(sin,ter,pre,(nada,swims)).
vrb(plu,ter,pre,(nadan,swim)).
vrb(sin,pri,pas,(nade,swam)).
vrb(plu,pri,pas,(nadamos,swam)).
vrb(sin,seg,pas,(nado,swam)).
vrb(plu,seg,pas,(nadaron,swam)).
vrb(sin,ter,pas,(nado,swam)).
vrb(plu,ter,pas,(nadaron,swam)).
%Guardar
vrb(sin,pri,pre,(guardo,keep)).
vrb(plu,pri,pre,(guardamos,keep)).
vrb(sin,seg,pre,(guarda,keep)).
vrb(plu,seg,pre,(guardan,keep)).
vrb(sin,ter,pre,(guarda,keeps)).
vrb(plu,ter,pre,(guardan,keep)).
vrb(sin,pri,pas,(guarde,kept)).
vrb(plu,pri,pas,(guardamos,kept)).
vrb(sin,seg,pas,(guardo,kept)).
vrb(plu,seg,pas,(guardaron,kept)).
vrb(sin,ter,pas,(guardo,kept)).
vrb(plu,ter,pas,(guardaron,kept)).
%Salvar
vrb(sin,pri,pre,(salvo,save)).
vrb(plu,pri,pre,(salvamos,save)).
vrb(sin,seg,pre,(salva,save)).
vrb(plu,seg,pre,(salvan,save)).
vrb(sin,ter,pre,(salva,saves)).
vrb(plu,ter,pre,(salvan,save)).
vrb(sin,pri,pas,(salve,saved)).
vrb(plu,pri,pas,(salvamos,saved)).
vrb(sin,seg,pas,(salvo,saved)).
vrb(plu,seg,pas,(salvaron,saved)).
vrb(sin,ter,pas,(salvo,saved)).
vrb(plu,ter,pas,(salvaron,saved)).
%Registrar
vrb(sin,pri,pre,(registro,register)).
vrb(plu,pri,pre,(registramos,register)).
vrb(sin,seg,pre,(registra,register)).
vrb(plu,seg,pre,(registran,register)).
vrb(sin,ter,pre,(registra,registers)).
vrb(plu,ter,pre,(registran,register)).
vrb(sin,pri,pas,(registre,registered)).
vrb(plu,pri,pas,(registramos,registered)).
vrb(sin,seg,pas,(registro,registered)).
vrb(plu,seg,pas,(registraron,registered)).
vrb(sin,ter,pas,(registro,registered)).
vrb(plu,ter,pas,(registraron,registered)).
%Pensar
vrb(sin,pri,pre,(pienso,think)).
vrb(plu,pri,pre,(pensamos,think)).
vrb(sin,seg,pre,(piensa,think)).
vrb(plu,seg,pre,(piensan,think)).
vrb(sin,ter,pre,(piensa,thinks)).
vrb(plu,ter,pre,(piensan,think)).
vrb(sin,pri,pas,(pense,though)).
vrb(plu,pri,pas,(pensamos,though)).
vrb(sin,seg,pas,(penso,though)).
vrb(plu,seg,pas,(pensaron,though)).
vrb(sin,ter,pas,(penso,though)).
vrb(plu,ter,pas,(pensaron,though)).
%Traducir
vrb(sin,pri,pre,(traduzco,translate)).
vrb(plu,pri,pre,(traducimos,translate)).
vrb(sin,seg,pre,(traduce,translate)).
vrb(plu,seg,pre,(traducen,translate)).
vrb(sin,ter,pre,(traduce,translates)).
vrb(plu,ter,pre,(traducen,translate)).
vrb(sin,pri,pas,(traduje,translated)).
vrb(plu,pri,pas,(tradujimos,translated)).
vrb(sin,seg,pas,(tradujo,translated)).
vrb(plu,seg,pas,(tradujeron,translated)).
vrb(sin,ter,pas,(tradujo,translated)).
vrb(plu,ter,pas,(tradujeron,translated)).
%Imprimir
vrb(sin,pri,pre,(imprimo,print)).
vrb(plu,pri,pre,(imprimimos,print)).
vrb(sin,seg,pre,(imprime,print)).
vrb(plu,seg,pre,(imprimen,print)).
vrb(sin,ter,pre,(imprime,prints)).
vrb(plu,ter,pre,(imprimen,print)).
vrb(sin,pri,pas,(imprimi,printed)).
vrb(plu,pri,pas,(imprimimos,printed)).
vrb(sin,seg,pas,(imprimio,printed)).
vrb(plu,seg,pas,(imprimieron,printed)).
vrb(sin,ter,pas,(imprimio,printed)).
vrb(plu,ter,pas,(imprimieron,printed)).
%Volar
vrb(sin,pri,pre,(vuelo,fly)).
vrb(plu,pri,pre,(volamos,fly)).
vrb(sin,seg,pre,(vuela,fly)).
vrb(plu,seg,pre,(vuelan,fly)).
vrb(sin,ter,pre,(vuela,flies)).
vrb(plu,ter,pre,(vuelan,fly)).
vrb(sin,pri,pas,(vole,flew)).
vrb(plu,pri,pas,(volamos,flew)).
vrb(sin,seg,pas,(volo,flew)).
vrb(plu,seg,pas,(volaron,flew)).
vrb(sin,ter,pas,(volo,flew)).
vrb(plu,ter,pas,(volaron,flew)).
%Hablar
vrb(sin,pri,pre,(hablo,talk)).
vrb(plu,pri,pre,(hablamos,talk)).
vrb(sin,seg,pre,(habla,talk)).
vrb(plu,seg,pre,(hablan,talk)).
vrb(sin,ter,pre,(habla,talks)).
vrb(plu,ter,pre,(hablan,talk)).
vrb(sin,pri,pas,(hable,talked)).
vrb(plu,pri,pas,(hablamos,talked)).
vrb(sin,seg,pas,(hablo,talked)).
vrb(plu,seg,pas,(hablaron,talked)).
vrb(sin,ter,pas,(hablo,talked)).
vrb(plu,ter,pas,(hablaron,talked)).
%Sentar
vrb(sin,pri,pre,(siento,sit)).
vrb(plu,pri,pre,(sentamos,sit)).
vrb(sin,seg,pre,(sienta,sit)).
vrb(plu,seg,pre,(sientan,sit)).
vrb(sin,ter,pre,(sienta,sits)).
vrb(plu,ter,pre,(sientan,sit)).
vrb(sin,pri,pas,(sente,sat)).
vrb(plu,pri,pas,(sentamos,sat)).
vrb(sin,seg,pas,(sento,sat)).
vrb(plu,seg,pas,(sentaron,sat)).
vrb(sin,ter,pas,(sento,sat)).
vrb(plu,ter,pas,(sentaron,sat)).
%Amar
vrb(sin,pri,pre,(amo,love)).
vrb(plu,pri,pre,(amamos,love)).
vrb(sin,seg,pre,(ama,love)).
vrb(plu,seg,pre,(aman,love)).
vrb(sin,ter,pre,(ama,loves)).
vrb(plu,ter,pre,(aman,love)).
vrb(sin,pri,pas,(ame,loved)).
vrb(plu,pri,pas,(amamos,loved)).
vrb(sin,seg,pas,(amo,loved)).
vrb(plu,seg,pas,(amaron,loved)).
vrb(sin,ter,pas,(amo,loved)).
vrb(plu,ter,pas,(amaron,loved)).
%Cocinar
vrb(sin,pri,pre,(cocino,cook)).
vrb(plu,pri,pre,(cocinamos,cook)).
vrb(sin,seg,pre,(cocina,cook)).
vrb(plu,seg,pre,(cocinan,cook)).
vrb(sin,ter,pre,(cocina,cooks)).
vrb(plu,ter,pre,(cocinan,cook)).
vrb(sin,pri,pas,(cocine,cooked)).
vrb(plu,pri,pas,(cocinamos,cooked)).
vrb(sin,seg,pas,(cocino,cooked)).
vrb(plu,seg,pas,(cocinaron,cooked)).
vrb(sin,ter,pas,(cocino,cooked)).
vrb(plu,ter,pas,(cocinaron,cooked)).
%Hornear
vrb(sin,pri,pre,(horneo,bake)).
vrb(plu,pri,pre,(horneamos,bake)).
vrb(sin,seg,pre,(hornea,bake)).
vrb(plu,seg,pre,(hornean,bake)).
vrb(sin,ter,pre,(hornea,bakes)).
vrb(plu,ter,pre,(hornean,bake)).
vrb(sin,pri,pas,(hornee,baked)).
vrb(plu,pri,pas,(horneamos,baked)).
vrb(sin,seg,pas,(horneo,baked)).
vrb(plu,seg,pas,(hornearon,baked)).
vrb(sin,ter,pas,(horneo,baked)).
vrb(plu,ter,pas,(hornearon,baked)).
%Ver
vrb(sin,pri,pre,(veo,see)).
vrb(plu,pri,pre,(vemos,see)).
vrb(sin,seg,pre,(ve,see)).
vrb(plu,seg,pre,(ven,see)).
vrb(sin,ter,pre,(ve,sees)).
vrb(plu,ter,pre,(ven,see)).
vrb(sin,pri,pas,(vi,saw)).
vrb(plu,pri,pas,(vimos,saw)).
vrb(sin,seg,pas,(vio,saw)).
vrb(plu,seg,pas,(vieron,saw)).
vrb(sin,ter,pas,(vio,saw)).
vrb(plu,ter,pas,(vieron,saw)).
%Mirar
vrb(sin,pri,pre,(miro,watch)).
vrb(plu,pri,pre,(miramos,watch)).
vrb(sin,seg,pre,(mira,watch)).
vrb(plu,seg,pre,(miran,watch)).
vrb(sin,ter,pre,(mira,watches)).
vrb(plu,ter,pre,(miran,watch)).
vrb(sin,pri,pas,(mire,watched)).
vrb(plu,pri,pas,(miraron,watched)).
vrb(sin,seg,pas,(miro,watched)).
vrb(plu,seg,pas,(miraron,watched)).
vrb(sin,ter,pas,(miro,watched)).
vrb(plu,ter,pas,(miraron,watched)).
%Observar
vrb(sin,pri,pre,(observo,observe)).
vrb(plu,pri,pre,(observamos,observe)).
vrb(sin,seg,pre,(observa,observe)).
vrb(plu,seg,pre,(observan,observe)).
vrb(sin,ter,pre,(observa,observes)).
vrb(plu,ter,pre,(observan,observe)).
vrb(sin,pri,pas,(observe,observed)).
vrb(plu,pri,pas,(observamos,observed)).
vrb(sin,seg,pas,(observo,observed)).
vrb(plu,seg,pas,(observaron,observed)).
vrb(sin,ter,pas,(observo,observed)).
vrb(plu,ter,pas,(observaron,observed)).
%Lavar
vrb(sin,pri,pre,(lavo,wash)).
vrb(plu,pri,pre,(lavamos,wash)).
vrb(sin,seg,pre,(lava,wash)).
vrb(plu,seg,pre,(lavan,wash)).
vrb(sin,ter,pre,(lava,washes)).
vrb(plu,ter,pre,(lavan,wash)).
vrb(sin,pri,pas,(lave,washed)).
vrb(plu,pri,pas,(lavamos,washed)).
vrb(sin,seg,pas,(lavo,washed)).
vrb(plu,seg,pas,(lavaron,washed)).
vrb(sin,ter,pas,(lavo,washed)).
vrb(plu,ter,pas,(lavaron,washed)).
%Traer
vrb(sin,pri,pre,(traigo,bring)).
vrb(plu,pri,pre,(traemos,bring)).
vrb(sin,seg,pre,(trae,bring)).
vrb(plu,seg,pre,(traen,bring)).
vrb(sin,ter,pre,(trae,brings)).
vrb(plu,ter,pre,(traen,bring)).
vrb(sin,pri,pas,(traje,brought)).
vrb(plu,pri,pas,(trajimos,brought)).
vrb(sin,seg,pas,(trajo,brought)).
vrb(plu,seg,pas,(trajeron,brought)).
vrb(sin,ter,pas,(trajo,brought)).
vrb(plu,ter,pas,(trajeron,brought)).
%Enseñar
vrb(sin,pri,pre,(enseño,teach)).
vrb(plu,pri,pre,(enseñamos,teach)).
vrb(sin,seg,pre,(enseña,teach)).
vrb(plu,seg,pre,(enseñan,teach)).
vrb(sin,ter,pre,(enseña,teachs)).
vrb(plu,ter,pre,(enseñan,teach)).
vrb(sin,pri,pas,(enseñe,taught)).
vrb(plu,pri,pas,(enseñamos,taught)).
vrb(sin,seg,pas,(enseño,taught)).
vrb(plu,seg,pas,(enseñaron,taught)).
vrb(sin,ter,pas,(enseño,taught)).
vrb(plu,ter,pas,(enseñaron,taught)).
%Añadir
vrb(sin,pri,pre,(añado,add)).
vrb(plu,pri,pre,(añadimos,add)).
vrb(sin,seg,pre,(añade,add)).
vrb(plu,seg,pre,(añaden,add)).
vrb(sin,ter,pre,(añade,adds)).
vrb(plu,ter,pre,(añaden,add)).
vrb(sin,pri,pas,(añadi,added)).
vrb(plu,pri,pas,(añadimos,added)).
vrb(sin,seg,pas,(añadio,added)).
vrb(plu,seg,pas,(añadieron,added)).
vrb(sin,ter,pas,(añadio,added)).
vrb(plu,ter,pas,(añadieron,added)).
%Montar
vrb(sin,pri,pre,(monto,ride)).
vrb(plu,pri,pre,(montamos,ride)).
vrb(sin,seg,pre,(monta,ride)).
vrb(plu,seg,pre,(montan,ride)).
vrb(sin,ter,pre,(monta,rides)).
vrb(plu,ter,pre,(montan,ride)).
vrb(sin,pri,pas,(monte,rode)).
vrb(plu,pri,pas,(montamos,rode)).
vrb(sin,seg,pas,(monto,rode)).
vrb(plu,seg,pas,(montaron,rode)).
vrb(sin,ter,pas,(monto,rode)).
vrb(plu,ter,pas,(montaron,rode)).
%Copiar
vrb(sin,pri,pre,(copio,copy)).
vrb(plu,pri,pre,(copiamos,copy)).
vrb(sin,seg,pre,(copia,copy)).
vrb(plu,seg,pre,(copian,copy)).
vrb(sin,ter,pre,(copia,copies)).
vrb(plu,ter,pre,(copian,copy)).
vrb(sin,pri,pas,(copie,copied)).
vrb(plu,pri,pas,(copiamos,copied)).
vrb(sin,seg,pas,(copio,copied)).
vrb(plu,seg,pas,(copiaron,copied)).
vrb(sin,ter,pas,(copio,copied)).
vrb(plu,ter,pas,(copiaron,copied)).
%Pegar
vrb(sin,pri,pre,(pego,paste)).
vrb(plu,pri,pre,(pegamos,paste)).
vrb(sin,seg,pre,(pega,paste)).
vrb(plu,seg,pre,(pegan,paste)).
vrb(sin,ter,pre,(pega,pastes)).
vrb(plu,ter,pre,(pegan,paste)).
vrb(sin,pri,pas,(pegue,pasted)).
vrb(plu,pri,pas,(pegamos,pasted)).
vrb(sin,seg,pas,(pego,pasted)).
vrb(plu,seg,pas,(pegaron,pasted)).
vrb(sin,ter,pas,(pego,pasted)).
vrb(plu,ter,pas,(pegaron,pasted)).
%Cortar
vrb(sin,pri,pre,(corto,cut)).
vrb(plu,pri,pre,(cortamos,cut)).
vrb(sin,seg,pre,(corta,cut)).
vrb(plu,seg,pre,(cortan,cut)).
vrb(sin,ter,pre,(corta,cuts)).
vrb(plu,ter,pre,(cortan,cut)).
vrb(sin,pri,pas,(corte,cut)).
vrb(plu,pri,pas,(cortamos,cut)).
vrb(sin,seg,pas,(corto,cut)).
vrb(plu,seg,pas,(cortaron,cut)).
vrb(sin,ter,pas,(corto,cut)).
vrb(plu,ter,pas,(cortaron,cut)).
%Doblar
vrb(sin,pri,pre,(doblo,bend)).
vrb(plu,pri,pre,(doblamos,bend)).
vrb(sin,seg,pre,(dobla,bend)).
vrb(plu,seg,pre,(doblan,bend)).
vrb(sin,ter,pre,(dobla,bends)).
vrb(plu,ter,pre,(doblan,bend)).
vrb(sin,pri,pas,(doble,bent)).
vrb(plu,pri,pas,(doblamos,bent)).
vrb(sin,seg,pas,(doblo,bent)).
vrb(plu,seg,pas,(doblaron,bent)).
vrb(sin,ter,pas,(doblo,bent)).
vrb(plu,ter,pas,(doblaron,bent)).
%Poner
vrb(sin,pri,pre,(pongo,put)).
vrb(plu,pri,pre,(ponemos,put)).
vrb(sin,seg,pre,(pone,put)).
vrb(plu,seg,pre,(ponen,put)).
vrb(sin,ter,pre,(pone,puts)).
vrb(plu,ter,pre,(ponen,put)).
vrb(sin,pri,pas,(puse,put)).
vrb(plu,pri,pas,(pusimos,put)).
vrb(sin,seg,pas,(puso,put)).
vrb(plu,seg,pas,(pusieron,put)).
vrb(sin,ter,pas,(puso,put)).
vrb(plu,ter,pas,(pusieron,put)).
%Llevar
vrb(sin,pri,pre,(llevo,take)).
vrb(plu,pri,pre,(llevamos,take)).
vrb(sin,seg,pre,(lleva,take)).
vrb(plu,seg,pre,(llevan,take)).
vrb(sin,ter,pre,(lleva,takes)).
vrb(plu,ter,pre,(llevan,take)).
vrb(sin,pri,pas,(lleve,took)).
vrb(plu,pri,pas,(llevamos,took)).
vrb(sin,seg,pas,(llevo,took)).
vrb(plu,seg,pas,(llevaron,took)).
vrb(sin,ter,pas,(llevo,took)).
vrb(plu,ter,pas,(llevaron,took)).
%Golpear
vrb(sin,pri,pre,(golpeo,hit)).
vrb(plu,pri,pre,(golpeamos,hit)).
vrb(sin,seg,pre,(golpea,hit)).
vrb(plu,seg,pre,(golpean,hit)).
vrb(sin,ter,pre,(golpea,hits)).
vrb(plu,ter,pre,(golpean,hit)).
vrb(sin,pri,pas,(golpee,hitted)).
vrb(plu,pri,pas,(golpeamos,hitted)).
vrb(sin,seg,pas,(golpeo,hitted)).
vrb(plu,seg,pas,(golpearon,hitted)).
vrb(sin,ter,pas,(golpeo,hitted)).
vrb(plu,ter,pas,(golpearon,hitted)).
%Morder
vrb(sin,pri,pre,(muerdo,bite)).
vrb(plu,pri,pre,(mordimos,bite)).
vrb(sin,seg,pre,(muerde,bite)).
vrb(plu,seg,pre,(muerden,bite)).
vrb(sin,ter,pre,(muerde,bites)).
vrb(plu,ter,pre,(muerden,bite)).
vrb(sin,pri,pas,(mordi,bit)).
vrb(plu,pri,pas,(mordimos,bit)).
vrb(sin,seg,pas,(mordio,bit)).
vrb(plu,seg,pas,(mordieron,bit)).
vrb(sin,ter,pas,(mordio,bit)).
vrb(plu,ter,pas,(mordieron,bit)).
%Agradecer
vrb(sin,pri,pre,(agradrezco,thank)).
vrb(plu,pri,pre,(agradecemos,thank)).
vrb(sin,seg,pre,(agradece,thank)).
vrb(plu,seg,pre,(agradecen,thank)).
vrb(sin,ter,pre,(agradece,thanks)).
vrb(plu,ter,pre,(agradecen,thank)).
vrb(sin,pri,pas,(agradeci,thanked)).
vrb(plu,pri,pas,(agradecimos,thanked)).
vrb(sin,seg,pas,(agradecio,thanked)).
vrb(plu,seg,pas,(agradecieron,thanked)).
vrb(sin,ter,pas,(agradecio,thanked)).
vrb(plu,ter,pas,(agradecieron,thanked)).
%Morir
vrb(sin,pri,pre,(muero,die)).
vrb(plu,pri,pre,(morimos,die)).
vrb(sin,seg,pre,(muere,die)).
vrb(plu,seg,pre,(mueren,die)).
vrb(sin,ter,pre,(muere,dies)).
vrb(plu,ter,pre,(mueren,die)).
vrb(sin,pri,pas,(mori,died)).
vrb(plu,pri,pas,(morimos,died)).
vrb(sin,seg,pas,(murio,died)).
vrb(plu,seg,pas,(murieron,died)).
vrb(sin,ter,pas,(murio,died)).
vrb(plu,ter,pas,(murieron,died)).
